### ISSUE TITLE
Implement v2 of mgconsole UX

### ISSUE THREAD

**Issue by gitbuda** [memgraph/mgconsole#79]
### TODOs

- [ ] progress indicator for the long-running queries
- [ ] interacting with results
- [ ] funny error handling

### Inspiration

* https://github.com/rothgar/awesome-tuis
* https://github.com/mgramin/awesome-db-tools?tab=readme-ov-file#cli
